version: '3'

services:
  reverse-proxy:
    image: traefik:v2.7
    command: 
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false 
      - --providers.file.filename=/etc/traefik_providers/file_provider.yml
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./deploy/file_provider.yml:/etc/traefik_providers/file_provider.yml
      
  worker1:
    build:
      context: .
      dockerfile: Dockerfile
      
  worker2:
    build:
      context: .
      dockerfile: Dockerfile

  worker3:
    build:
      context: .
      dockerfile: Dockerfile

  worker4:
    build:
      context: .
      dockerfile: Dockerfile
