version: "3.9"
services:
  allinone:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "56789:56789"
    volumes:
      - ./WebServerResources:/usr/local/apache2/htdocs/WebObjects/wodockerapp.woa/Contents/WebServerResources
      - ./deploy/woconfig:/opt/Local/Library/WebObjects/Configuration
